#!/usr/bin/env bash

update() {
    for dir in ~/.n2 ~/.m2*; do
        if [ -d "$dir" ]; then
            (
                echo -e "Updating \e[033m$dir\e[0m"
                cd "$dir"
                git pull
            )
        fi
    done
}

case "$1" in
    update)
        update
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
        ;;
esac
