#!/usr/bin/env bash

function do_update {
    for dir in ~/.n2 ~/.m2*; do
        if [ -d "$dir" ]; then
            (
                echo
                echo -e "Updating \e[033m$dir\e[0m"
                echo
                cd "$dir"
                git pull
            )
        fi
    done
}

function do_status {
    for dir in ~/.n2 ~/.m2*; do
        if [ -d "$dir" ]; then
            (
                echo
                echo -e "Checking \e[033m$dir\e[0m"
                echo
                cd "$dir"
                git status
            )
        fi
    done
}

function do_man {
    man n2
}

function do_link_gitconfigs {
    local IFS index target link linkdir
    IFS=:
    linkdir="$__N2_DIR/volatile/git"

    rm -rf "$linkdir/link"*
    mkdir -p "$linkdir"

    index=0
    for m2_dir in $__M2_DIRS; do
        target="$m2_dir/git/config"

        if ! [ -f "$target" ]; then
            continue
        fi

        link="$linkdir/link$index"
        cp -s "$target" "$link"
        let index+=1
        if [ "$index" -gt 4 ]; then
            echo "You have too many M2 git configs!" >&2
            exit 1
        fi
    done
}

function do_create_n2 {
    local m2_dir
    m2_dir="$HOME/.m2-00-demo"

    echo
    echo -e "Creating a demo M2 dir \e[033m$m2_dir\e[0m"
    echo

    if [ -e "$m2_dir" ]; then
        echo -e "\e[031mAlready exists. Giving up.\e[0m"
        return 1
    fi

    cp -vr "$__N2_DIR/m2_demo" "$m2_dir"

    echo
    echo Wrote "$m2_dir".
    echo You can now explore the directory and start version-control it.
    echo
}

case "$1" in
    update)
        do_update
        ;;
    status)
        do_status
        ;;
    help | info | '?')
        do_man
        ;;
    link-gitconfigs)
        do_link_gitconfigs
        ;;
    create-m2)
        do_create_n2
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
        ;;
esac
