#!/usr/bin/env bash

function do_update {
    for dir in ~/.n2 ~/.m2*; do
        if [ -d "$dir" ]; then
            (
                echo -e "Updating \e[033m$dir\e[0m"
                cd "$dir"
                git pull
            )
        fi
    done
}

function do_status {
    for dir in ~/.n2 ~/.m2*; do
        if [ -d "$dir" ]; then
            (
                echo -e "Checking \e[033m$dir\e[0m"
                cd "$dir"
                git status
            )
        fi
    done
}

function do_help {
    man n2
}

case "$1" in
    update)
        do_update
        ;;
    status)
        do_status
        ;;
    help)
        do_help
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
        ;;
esac
